services:
  - docker
notifications:
  email: false
  slack: thevaultersinc:G0bhEMi23csD2mWXqabFwMFS
dist: xenial
language: cpp
os: linux
compiler:
- clang
cache: ccache
before_install:
  - docker pull doscode/merger-build-env:latest
  - docker run -d --name build-env --rm -i -t doscode/merger-build-env:latest bash
install:
script:
  - docker exec build-env sh -c "
    mkdir -p workspace && cd workspace;
    git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/tethys/tethys.git;
    cd tethys;
    git submodule update --init;
    mkdir -p build;
    "
  - docker exec build-env sh -c "
    cd workspace/tethys;
    ./tethys_install.sh
    "
  - docker exec build-env sh -c "
    cd workspace/tethys/build;
    cp ../scripts/run-clang-tidy.py run-clang-tidy.py;
    python3 run-clang-tidy.py;
    "
